title:            nerdondon
description:      From information security to information on securities
disqus_shortname: nerdondonblog
#reading_time:     true
words_per_minute: 200
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: "http://blog.nerdondon.com"

# Owner/author information
owner:
  name:           Will Sean Don
  avatar:         "headshot_avatar.jpg"
  bio:            "Dev. Finance. Security."
  email:          "willdon@nerdondon.com"
  # Social networking links used in footer. Update and remove as you like.
  twitter:        "@nerdondon"
  facebook:
  github:         "nerdondon"
  stackexchange:
  linkedin:
  instagram:
  flickr:
  tumblr:
  facebook:
  google_plus:

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Los_Angeles
future:      false
highlighter: rouge
markdown:    kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - LICENSE
  - README
  - README.md
  - Rakefile
  - Rakefile.rb
  - test
  - config
  - config.rb
  - gulpfile.js
  - lib
  - samples
  - log
  - node_modules
  - package.json
  - spec
  - tmp
